server:
  # ????
  port: 8090

#h2??
#??SQL???????
spring:
  jpa:
    show-sql: true
    #??ddl??
    hibernate:
      ddl-auto: update
  #    database-platform: org.hibernate.dialect.H2Dialect
  ##???????
  datasource:
    driverClassName: org.h2.Driver
    #??????????
    url: jdbc:h2:mem:test
    #?????????
    username: h2
    password: h2
    ##???????
    #????????????????????resources/db/schema.sql???????????????
#    schema: classpath:db/schema.sql
    #????????????????????resources/db/data.sql?????????????
#    data: classpath:db/data.sql
    ##h2 web console??
    #???????????h2
#    platform: h2
  # ???????h2 web consloe????????????????????
  h2:
    console:
      settings:
        web-allow-others: true
      #????????????YOUR_URL/h2??h2 web consloe?YOUR_URL???????URl?
      path: /h2
      #???????????????h2 web consloe??????????????????????h2 web consloe???????false?
      enabled: true

logging:
  level:
    com.cloud.war.scheduler: debug
